#!/bin/bash

xrandr --output HDMI-0 --off
xrandr --output HDMI-0 --auto
xrandr --output HDMI-0 --right-of LVDS-0 
killall plasmashell
kstart plasmashell &> /dev/null
feh --bg-scale ~/Pictures/wallpaper.png
